// Code generated by coz. DO NOT EDIT.
/**
 * Helper modules
 * @module helpers
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const RMSDetector_ = require('./RMSDetector')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.RMSDetector = _d(RMSDetector_)

module.exports = {
  RMSDetector: _d(RMSDetector_),
}
