// Code generated by coz. DO NOT EDIT.
/**
 * Helper modules
 * @module helpers
 */
'use strict'

const RMSDetector_ = require('./RMSDetector')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.RMSDetector = RMSDetector_

module.exports = {
  RMSDetector: RMSDetector_,
}
