// Code generated by coz. DO NOT EDIT.
/**
 * Audio utility
 * @module the-audio
 */
'use strict'

const TheAudio_ = require('./TheAudio')
const create_ = require('./create')
const helpers_ = require('./helpers')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheAudio = TheAudio_
exports.create = create_
exports.helpers = helpers_

module.exports = default__
