// Code generated by coz. DO NOT EDIT.
/**
 * Audio utility
 * @module the-audio
 */
'use strict'

const _d = (m) => (m && 'default' in m) ? m.default : m

const TheAudio_ = require('./TheAudio')
const create_ = require('./create')
const helpers_ = require('./helpers')
const default__ = require('./default')

// `module.exports` overrides these `exports.*`, but still needs them for lebab (https://github.com/lebab/lebab)
exports.TheAudio = _d(TheAudio_)
exports.create = _d(create_)
exports.helpers = _d(helpers_)

module.exports = _d(default__)
